name: Release Process

on:
  workflow_dispatch:  # Allows admins to trigger the release manually

jobs:
  release:
    name: Squash Merge Dev → Main & Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ensure the correct version
          cache: 'npm'

      - name: Get Version from package.json
        id: package_version
        run: echo "VERSION=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_ENV

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # Adjust based on your Vite setup

      - name: Zip dist/ folder
        run: |
          cd dist
          zip -r ../release-v${{ env.VERSION }}.zip *
          cd ..

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Squash Merge Dev into Main
        run: |
          git checkout main
          git pull origin main
          git merge --squash origin/dev
          git commit -m "Release: Squashed merge from dev"
          git push origin main

      - name: Tag Release
        run: |
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: "Release v${{ env.VERSION }}"
          body: "Automated release for v${{ env.VERSION }}"
          draft: true
          files: |
            release-v${{ env.VERSION }}.zip
