name: Release Process

on:
  push:
    tags:
      - 'v**'

jobs:
  release:
    name: Release-o-matic
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch depth is required for tag operations

      - name: Extract version number from tag
        id: module_info
        run: |
          TAG_NAME=${{ github.ref_name }}
          TAG_VERSION=$(echo "$TAG_NAME" | cut -d 'v' -f2)  # Extract '1.2.3'
          echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV

      - name: Get Version from package.json
        run: | 
          VERSION=$(jq -r '.version' < ./package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          if ! test "$VERSION" == "$TAG_VERSION"; then
            echo "Version name is incorrect! Should be ${{env.VERSION}}, is ${{env.TAG_VERSION}}";
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Zip .dist/ folder
        run: (cd modules; for i in *; do zip -r "../${i%}-v$VERSION.zip" "$i"; done)

      - name: Copy module.json 
        run: (cd modules; for i in *; do cp "${i%}/.dist/module.json" "../$i.json"; done)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: "Release v${{ env.VERSION }}"
          body: "Automated release for v${{ env.VERSION }}"
          draft: true
          files: |
            rpgm*.zip
            rpgm*.json
